var annotated_dup =
[
    [ "AR", "namespace_a_r.html", "namespace_a_r" ],
    [ "FFmpeg", "namespace_f_fmpeg.html", "namespace_f_fmpeg" ],
    [ "Meta", "namespace_meta.html", "namespace_meta" ],
    [ "NativeWifi", "namespace_native_wifi.html", "namespace_native_wifi" ],
    [ "BatteryLow", "class_battery_low.html", "class_battery_low" ],
    [ "BatteryPercentage", "class_battery_percentage.html", "class_battery_percentage" ],
    [ "BatteryVoltage", "class_battery_voltage.html", "class_battery_voltage" ],
    [ "CameraFeedExample", "class_camera_feed_example.html", "class_camera_feed_example" ],
    [ "compass", "classcompass.html", "classcompass" ],
    [ "ControllerStatus", "class_controller_status.html", "class_controller_status" ],
    [ "DebugScript", "class_debug_script.html", "class_debug_script" ],
    [ "DisplayMessage", "class_display_message.html", "class_display_message" ],
    [ "DoxygenConfig", "class_doxygen_config.html", "class_doxygen_config" ],
    [ "DoxygenWindow", "class_doxygen_window.html", "class_doxygen_window" ],
    [ "DoxyRunner", "class_doxy_runner.html", "class_doxy_runner" ],
    [ "DoxyThreadSafeOutput", "class_doxy_thread_safe_output.html", "class_doxy_thread_safe_output" ],
    [ "DroneAltitude", "class_drone_altitude.html", "class_drone_altitude" ],
    [ "droneCamFrontController", "classdrone_cam_front_controller.html", "classdrone_cam_front_controller" ],
    [ "DroneConnect", "class_drone_connect.html", "class_drone_connect" ],
    [ "DroneController", "class_drone_controller.html", "class_drone_controller" ],
    [ "dronePitch", "classdrone_pitch.html", "classdrone_pitch" ],
    [ "droneRoll", "classdrone_roll.html", "classdrone_roll" ],
    [ "DroneStatus", "class_drone_status.html", "class_drone_status" ],
    [ "gMapsDrone", "classg_maps_drone.html", "classg_maps_drone" ],
    [ "GoogleMap", "class_google_map.html", "class_google_map" ],
    [ "GoogleMapLocation", "class_google_map_location.html", "class_google_map_location" ],
    [ "GoogleMapMarker", "class_google_map_marker.html", "class_google_map_marker" ],
    [ "GoogleMapPath", "class_google_map_path.html", "class_google_map_path" ],
    [ "Helper", "class_helper.html", "class_helper" ],
    [ "MarkerTrackerExample", "class_marker_tracker_example.html", "class_marker_tracker_example" ],
    [ "MaxBuffer", "class_max_buffer.html", "class_max_buffer" ],
    [ "PitchDegree", "class_pitch_degree.html", "class_pitch_degree" ],
    [ "RollDegree", "class_roll_degree.html", "class_roll_degree" ],
    [ "Wlan", "class_wlan.html", "class_wlan" ],
    [ "XInputTestCS", "class_x_input_test_c_s.html", null ]
];