var hierarchy =
[
    [ "FFmpeg.AutoGen.anon_10", "struct_f_fmpeg_1_1_auto_gen_1_1anon__10.html", null ],
    [ "FFmpeg.AutoGen.anon_12", "struct_f_fmpeg_1_1_auto_gen_1_1anon__12.html", null ],
    [ "FFmpeg.AutoGen.anon_16", "struct_f_fmpeg_1_1_auto_gen_1_1anon__16.html", null ],
    [ "FFmpeg.AutoGen.anon_17", "struct_f_fmpeg_1_1_auto_gen_1_1anon__17.html", null ],
    [ "AR.Drone.Avionics.Tools.Arithmetics", "class_a_r_1_1_drone_1_1_avionics_1_1_tools_1_1_arithmetics.html", null ],
    [ "AR.Drone.Client.Command.AtCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_at_command.html", [
      [ "AR.Drone.Client.Command.CalibrateCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_calibrate_command.html", null ],
      [ "AR.Drone.Client.Command.ConfigCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_config_command.html", null ],
      [ "AR.Drone.Client.Command.ConfigIdsCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_config_ids_command.html", null ],
      [ "AR.Drone.Client.Command.ControlCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_control_command.html", null ],
      [ "AR.Drone.Client.Command.FlatTrimCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_flat_trim_command.html", null ],
      [ "AR.Drone.Client.Command.ProgressCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_progress_command.html", null ],
      [ "AR.Drone.Client.Command.ProgressWithMagnetoCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_progress_with_magneto_command.html", null ],
      [ "AR.Drone.Client.Command.RefCommand", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_ref_command.html", null ]
    ] ],
    [ "FFmpeg.AutoGen.av_intfloat32", "struct_f_fmpeg_1_1_auto_gen_1_1av__intfloat32.html", null ],
    [ "FFmpeg.AutoGen.av_intfloat64", "struct_f_fmpeg_1_1_auto_gen_1_1av__intfloat64.html", null ],
    [ "FFmpeg.AutoGen.AVAudioFifo", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_audio_fifo.html", null ],
    [ "FFmpeg.AutoGen.AVBitStreamFilter", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_bit_stream_filter.html", null ],
    [ "FFmpeg.AutoGen.AVBitStreamFilterContext", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_bit_stream_filter_context.html", null ],
    [ "FFmpeg.AutoGen.AVBPrint", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_b_print.html", null ],
    [ "FFmpeg.AutoGen.AVBuffer", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_buffer.html", null ],
    [ "FFmpeg.AutoGen.AVBufferPool", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_buffer_pool.html", null ],
    [ "FFmpeg.AutoGen.AVBufferRef", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_buffer_ref.html", null ],
    [ "FFmpeg.AutoGen.AVChapter", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_chapter.html", null ],
    [ "FFmpeg.AutoGen.AVClass", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_class.html", null ],
    [ "FFmpeg.AutoGen.AVCodec", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec.html", null ],
    [ "FFmpeg.AutoGen.AVCodecContext", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec_context.html", null ],
    [ "FFmpeg.AutoGen.AVCodecDefault", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec_default.html", null ],
    [ "FFmpeg.AutoGen.AVCodecDescriptor", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec_descriptor.html", null ],
    [ "FFmpeg.AutoGen.AVCodecInternal", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec_internal.html", null ],
    [ "FFmpeg.AutoGen.AVCodecParser", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec_parser.html", null ],
    [ "FFmpeg.AutoGen.AVCodecParserContext", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec_parser_context.html", null ],
    [ "FFmpeg.AutoGen.AVCodecTag", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_codec_tag.html", null ],
    [ "FFmpeg.AutoGen.AVComponentDescriptor", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_component_descriptor.html", null ],
    [ "FFmpeg.AutoGen.AVDeviceCapabilitiesQuery", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_device_capabilities_query.html", null ],
    [ "FFmpeg.AutoGen.AVDeviceInfo", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_device_info.html", null ],
    [ "FFmpeg.AutoGen.AVDeviceInfoList", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_device_info_list.html", null ],
    [ "FFmpeg.AutoGen.AVDeviceRect", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_device_rect.html", null ],
    [ "FFmpeg.AutoGen.AVDictionary", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_dictionary.html", null ],
    [ "FFmpeg.AutoGen.AVDictionaryEntry", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_dictionary_entry.html", null ],
    [ "FFmpeg.AutoGen.AVFifoBuffer", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_fifo_buffer.html", null ],
    [ "FFmpeg.AutoGen.AVFilter", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter.html", null ],
    [ "FFmpeg.AutoGen.AVFilterBuffer", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_buffer.html", null ],
    [ "FFmpeg.AutoGen.AVFilterBufferRef", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_buffer_ref.html", null ],
    [ "FFmpeg.AutoGen.AVFilterBufferRefAudioProps", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_buffer_ref_audio_props.html", null ],
    [ "FFmpeg.AutoGen.AVFilterBufferRefVideoProps", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_buffer_ref_video_props.html", null ],
    [ "FFmpeg.AutoGen.AVFilterChannelLayouts", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_channel_layouts.html", null ],
    [ "FFmpeg.AutoGen.AVFilterCommand", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_command.html", null ],
    [ "FFmpeg.AutoGen.AVFilterContext", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_context.html", null ],
    [ "FFmpeg.AutoGen.AVFilterFormats", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_formats.html", null ],
    [ "FFmpeg.AutoGen.AVFilterGraph", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_graph.html", null ],
    [ "FFmpeg.AutoGen.AVFilterGraphInternal", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_graph_internal.html", null ],
    [ "FFmpeg.AutoGen.AVFilterInOut", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_in_out.html", null ],
    [ "FFmpeg.AutoGen.AVFilterInternal", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_internal.html", null ],
    [ "FFmpeg.AutoGen.AVFilterLink", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_link.html", null ],
    [ "FFmpeg.AutoGen.AVFilterPad", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_pad.html", null ],
    [ "FFmpeg.AutoGen.AVFilterPool", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_filter_pool.html", null ],
    [ "FFmpeg.AutoGen.AVFormatContext", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_format_context.html", null ],
    [ "FFmpeg.AutoGen.AVFormatInternal", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_format_internal.html", null ],
    [ "FFmpeg.AutoGen.AVFrac", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_frac.html", null ],
    [ "FFmpeg.AutoGen.AVFrame", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_frame.html", null ],
    [ "FFmpeg.AutoGen.AVFrameSideData", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_frame_side_data.html", null ],
    [ "FFmpeg.AutoGen.AVHWAccel", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_h_w_accel.html", null ],
    [ "FFmpeg.AutoGen.AVIndexEntry", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_index_entry.html", null ],
    [ "FFmpeg.AutoGen.AVInputFormat", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_input_format.html", null ],
    [ "FFmpeg.AutoGen.AVIOContext", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_i_o_context.html", null ],
    [ "FFmpeg.AutoGen.AVIOInterruptCB", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_i_o_interrupt_c_b.html", null ],
    [ "FFmpeg.AutoGen.AVOption", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_option.html", null ],
    [ "FFmpeg.AutoGen.AVOptionRange", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_option_range.html", null ],
    [ "FFmpeg.AutoGen.AVOptionRanges", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_option_ranges.html", null ],
    [ "FFmpeg.AutoGen.AVOutputFormat", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_output_format.html", null ],
    [ "FFmpeg.AutoGen.AVPacket", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_packet.html", null ],
    [ "FFmpeg.AutoGen.AVPacketList", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_packet_list.html", null ],
    [ "FFmpeg.AutoGen.AVPacketSideData", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_packet_side_data.html", null ],
    [ "FFmpeg.AutoGen.AVPanScan", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_pan_scan.html", null ],
    [ "FFmpeg.AutoGen.AVPicture", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_picture.html", null ],
    [ "FFmpeg.AutoGen.AVPixFmtDescriptor", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_pix_fmt_descriptor.html", null ],
    [ "FFmpeg.AutoGen.AVProbeData", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_probe_data.html", null ],
    [ "FFmpeg.AutoGen.AVProfile", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_profile.html", null ],
    [ "FFmpeg.AutoGen.AVProgram", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_program.html", null ],
    [ "FFmpeg.AutoGen.AVRational", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_rational.html", null ],
    [ "FFmpeg.AutoGen.AVResampleContext", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_resample_context.html", null ],
    [ "FFmpeg.AutoGen.AVStream", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_stream.html", null ],
    [ "FFmpeg.AutoGen.AVSubtitle", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_subtitle.html", null ],
    [ "FFmpeg.AutoGen.AVSubtitleRect", "struct_f_fmpeg_1_1_auto_gen_1_1_a_v_subtitle_rect.html", null ],
    [ "AR.Drone.Data.Navigation.Battery", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_battery.html", null ],
    [ "BinaryReader", null, [
      [ "AR.Drone.Media.PacketReader", "class_a_r_1_1_drone_1_1_media_1_1_packet_reader.html", null ]
    ] ],
    [ "BinaryWriter", null, [
      [ "AR.Drone.Media.PacketWriter", "class_a_r_1_1_drone_1_1_media_1_1_packet_writer.html", null ]
    ] ],
    [ "AR.Drone.Infrastructure.ConcurrentQueueExtensions", "class_a_r_1_1_drone_1_1_infrastructure_1_1_concurrent_queue_extensions.html", null ],
    [ "AR.Drone.Client.Configuration.ConfigurationAcquisition", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_configuration_acquisition.html", null ],
    [ "AR.Drone.Data.ConversionHelper", "class_a_r_1_1_drone_1_1_data_1_1_conversion_helper.html", null ],
    [ "NativeWifi.Wlan.Dot11Ssid", "struct_native_wifi_1_1_wlan_1_1_dot11_ssid.html", null ],
    [ "DoxygenConfig", "class_doxygen_config.html", null ],
    [ "DoxyRunner", "class_doxy_runner.html", null ],
    [ "DoxyThreadSafeOutput", "class_doxy_thread_safe_output.html", null ],
    [ "AR.Drone.Avionics.Tools.Time.Duration", "class_a_r_1_1_drone_1_1_avionics_1_1_tools_1_1_time_1_1_duration.html", null ],
    [ "EditorWindow", null, [
      [ "DoxygenWindow", "class_doxygen_window.html", null ]
    ] ],
    [ "AR.Drone.Data.EnumExtensions", "class_a_r_1_1_drone_1_1_data_1_1_enum_extensions.html", null ],
    [ "AR.Drone.Client.EnumHelper", "class_a_r_1_1_drone_1_1_client_1_1_enum_helper.html", null ],
    [ "Exception", null, [
      [ "AR.Drone.Video.Exceptions.VideoConverterException", "class_a_r_1_1_drone_1_1_video_1_1_exceptions_1_1_video_converter_exception.html", null ],
      [ "AR.Drone.Video.Exceptions.VideoDecoderException", "class_a_r_1_1_drone_1_1_video_1_1_exceptions_1_1_video_decoder_exception.html", null ],
      [ "NativeWifi.Wlan.WlanException", "class_native_wifi_1_1_wlan_1_1_wlan_exception.html", null ]
    ] ],
    [ "AR.Drone.Avionics.Tools.Time.Expiration", "class_a_r_1_1_drone_1_1_avionics_1_1_tools_1_1_time_1_1_expiration.html", null ],
    [ "FFmpeg.AutoGen.FFmpegInvoke", "class_f_fmpeg_1_1_auto_gen_1_1_f_fmpeg_invoke.html", null ],
    [ "AR.Drone.Client.Configuration.FlightAnimation", "struct_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_flight_animation.html", null ],
    [ "AR.Drone.Avionics.Apparatus.Input.Limits.Gaz", "class_a_r_1_1_drone_1_1_avionics_1_1_apparatus_1_1_input_1_1_limits_1_1_gaz.html", null ],
    [ "GoogleMapLocation", "class_google_map_location.html", null ],
    [ "GoogleMapMarker", "class_google_map_marker.html", null ],
    [ "GoogleMapPath", "class_google_map_path.html", null ],
    [ "Helper", "class_helper.html", null ],
    [ "IDisposable", null, [
      [ "AR.Drone.Infrastructure.DisposableBase", "class_a_r_1_1_drone_1_1_infrastructure_1_1_disposable_base.html", [
        [ "AR.Drone.Infrastructure.WorkerBase", "class_a_r_1_1_drone_1_1_infrastructure_1_1_worker_base.html", [
          [ "AR.Drone.Avionics.Autopilot", "class_a_r_1_1_drone_1_1_avionics_1_1_autopilot.html", null ],
          [ "AR.Drone.Client.Command.CommandSender", "class_a_r_1_1_drone_1_1_client_1_1_command_1_1_command_sender.html", null ],
          [ "AR.Drone.Client.DroneClient", "class_a_r_1_1_drone_1_1_client_1_1_drone_client.html", null ],
          [ "AR.Drone.Client.Navigation.NavdataAcquisition", "class_a_r_1_1_drone_1_1_client_1_1_navigation_1_1_navdata_acquisition.html", null ],
          [ "AR.Drone.Client.Video.VideoAcquisition", "class_a_r_1_1_drone_1_1_client_1_1_video_1_1_video_acquisition.html", null ],
          [ "AR.Drone.Media.PacketRecorder", "class_a_r_1_1_drone_1_1_media_1_1_packet_recorder.html", null ],
          [ "AR.Drone.Video.VideoPacketDecoderWorker", "class_a_r_1_1_drone_1_1_video_1_1_video_packet_decoder_worker.html", null ]
        ] ],
        [ "AR.Drone.Video.VideoConverter", "class_a_r_1_1_drone_1_1_video_1_1_video_converter.html", null ],
        [ "AR.Drone.Video.VideoDecoder", "class_a_r_1_1_drone_1_1_video_1_1_video_decoder.html", null ],
        [ "AR.Drone.Video.VideoPacketDecoder", "class_a_r_1_1_drone_1_1_video_1_1_video_packet_decoder.html", null ]
      ] ]
    ] ],
    [ "AR.Drone.Avionics.Apparatus.Input", "struct_a_r_1_1_drone_1_1_avionics_1_1_apparatus_1_1_input.html", null ],
    [ "AR.Drone.Avionics.Objectives.IntentObtainers.Intent", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_intent.html", [
      [ "AR.Drone.Avionics.Objectives.IntentObtainers.IntentObtainer", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_intent_obtainer.html", [
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.Altitude", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_altitude.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.EmergencyResetting", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_emergency_resetting.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.EmergencySetting", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_emergency_setting.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.FlatTrimming", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_flat_trimming.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.Heading", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_heading.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.Hovering", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_hovering.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.Landing", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_landing.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.SetGaz", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_set_gaz.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.SetPitch", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_set_pitch.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.SetRoll", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_set_roll.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.SetYaw", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_set_yaw.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.Takingoff", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_takingoff.html", null ],
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.VelocityIntent", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_velocity_intent.html", [
          [ "AR.Drone.Avionics.Objectives.IntentObtainers.VelocityX", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_velocity_x.html", null ],
          [ "AR.Drone.Avionics.Objectives.IntentObtainers.VelocityY", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_velocity_y.html", null ]
        ] ]
      ] ]
    ] ],
    [ "AR.Drone.Infrastructure.InteropHelper", "class_a_r_1_1_drone_1_1_infrastructure_1_1_interop_helper.html", null ],
    [ "AR.Drone.Avionics.Objectives.IntentObtainers.IObtainer", "interface_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_i_obtainer.html", [
      [ "AR.Drone.Avionics.Objectives.IntentObtainers.IEarlyObtainer", "interface_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_i_early_obtainer.html", [
        [ "AR.Drone.Avionics.Objectives.IntentObtainers.IntentObtainer", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_intent_obtainers_1_1_intent_obtainer.html", null ],
        [ "AR.Drone.Avionics.Objectives.Objective", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_objective.html", [
          [ "AR.Drone.Avionics.Objectives.Emergency", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_emergency.html", null ],
          [ "AR.Drone.Avionics.Objectives.EmergencyReset", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_emergency_reset.html", null ],
          [ "AR.Drone.Avionics.Objectives.FlatTrim", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_flat_trim.html", null ],
          [ "AR.Drone.Avionics.Objectives.Hover", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_hover.html", null ],
          [ "AR.Drone.Avionics.Objectives.Land", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_land.html", null ],
          [ "AR.Drone.Avionics.Objectives.Takeoff", "class_a_r_1_1_drone_1_1_avionics_1_1_objectives_1_1_takeoff.html", null ]
        ] ]
      ] ]
    ] ],
    [ "AR.Drone.Client.LedAnimation", "struct_a_r_1_1_drone_1_1_client_1_1_led_animation.html", null ],
    [ "AR.Drone.Avionics.Apparatus.Input.Limits", "class_a_r_1_1_drone_1_1_avionics_1_1_apparatus_1_1_input_1_1_limits.html", null ],
    [ "AR.Drone.Data.Navigation.Magneto", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_magneto.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Math.matrix33_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_math_1_1matrix33__t.html", null ],
    [ "MaxBuffer< float >", "class_max_buffer.html", null ],
    [ "DisplayMessage.MessageItem", "class_display_message_1_1_message_item.html", null ],
    [ "MonoBehaviour", null, [
      [ "BatteryLow", "class_battery_low.html", null ],
      [ "BatteryPercentage", "class_battery_percentage.html", null ],
      [ "BatteryVoltage", "class_battery_voltage.html", null ],
      [ "CameraFeedExample", "class_camera_feed_example.html", null ],
      [ "compass", "classcompass.html", null ],
      [ "ControllerStatus", "class_controller_status.html", null ],
      [ "DebugScript", "class_debug_script.html", null ],
      [ "DisplayMessage", "class_display_message.html", null ],
      [ "DroneAltitude", "class_drone_altitude.html", null ],
      [ "droneCamFrontController", "classdrone_cam_front_controller.html", null ],
      [ "DroneConnect", "class_drone_connect.html", null ],
      [ "DroneController", "class_drone_controller.html", null ],
      [ "dronePitch", "classdrone_pitch.html", null ],
      [ "droneRoll", "classdrone_roll.html", null ],
      [ "DroneStatus", "class_drone_status.html", null ],
      [ "gMapsDrone", "classg_maps_drone.html", null ],
      [ "GoogleMap", "class_google_map.html", null ],
      [ "MarkerTrackerExample", "class_marker_tracker_example.html", null ],
      [ "Meta.Apps.MetaSDKGuide.HudCube", "class_meta_1_1_apps_1_1_meta_s_d_k_guide_1_1_hud_cube.html", null ],
      [ "Meta.Apps.MetaSDKGuide.Quit", "class_meta_1_1_apps_1_1_meta_s_d_k_guide_1_1_quit.html", null ],
      [ "Meta.Apps.SDKGuide.GazeableTestScript", "class_meta_1_1_apps_1_1_s_d_k_guide_1_1_gazeable_test_script.html", null ],
      [ "Meta.Apps.SDKGuide.OnGrabTestScript", "class_meta_1_1_apps_1_1_s_d_k_guide_1_1_on_grab_test_script.html", null ],
      [ "Meta.Apps.SDKGuide.OnPinchTestScript", "class_meta_1_1_apps_1_1_s_d_k_guide_1_1_on_pinch_test_script.html", null ],
      [ "Meta.Apps.SDKGuide.OnSwipeTestScript", "class_meta_1_1_apps_1_1_s_d_k_guide_1_1_on_swipe_test_script.html", null ],
      [ "Meta.Apps.SDKGuide.OnTouchEnterTestScript", "class_meta_1_1_apps_1_1_s_d_k_guide_1_1_on_touch_enter_test_script.html", null ],
      [ "PitchDegree", "class_pitch_degree.html", null ],
      [ "RollDegree", "class_roll_degree.html", null ],
      [ "Wlan", "class_wlan.html", null ],
      [ "XInputTestCS", "class_x_input_test_c_s.html", null ]
    ] ],
    [ "FFmpeg.AutoGen.MpegEncContext", "struct_f_fmpeg_1_1_auto_gen_1_1_mpeg_enc_context.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_adc_data_frame_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__adc__data__frame__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_altitude_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__altitude__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_cks_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__cks__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_demo_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__demo__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_euler_angles_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__euler__angles__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_games_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__games__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_gyros_offsets_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__gyros__offsets__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_hdvideo_stream_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__hdvideo__stream__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_kalman_pressure_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__kalman__pressure__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_magneto_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__magneto__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.navdata_option_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1navdata__option__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_phys_measures_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__phys__measures__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_pressure_raw_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__pressure__raw__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_pwm_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__pwm__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_raw_measures_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__raw__measures__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_rc_references_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__rc__references__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_references_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__references__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.navdata_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1navdata__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_time_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__time__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_trackers_send_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__trackers__send__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_trims_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__trims__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_video_stream_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__video__stream__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_vision_detect_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__vision__detect__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_vision_of_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__vision__of__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_vision_perf_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__vision__perf__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_vision_raw_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__vision__raw__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_vision_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__vision__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_watchdog_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__watchdog__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_wifi_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__wifi__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.navdata_wind_speed_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1navdata__wind__speed__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.NavdataBag", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_navdata_bag.html", null ],
    [ "AR.Drone.Data.Navigation.Native.NavdataBagParser", "class_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_navdata_bag_parser.html", null ],
    [ "AR.Drone.Data.Navigation.NavdataConverter", "class_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_navdata_converter.html", null ],
    [ "AR.Drone.Data.Navigation.NavigationData", "class_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_navigation_data.html", null ],
    [ "AR.Drone.Data.NavigationPacket", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_packet.html", null ],
    [ "AR.Drone.Data.Navigation.NavigationPacketParser", "class_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_navigation_packet_parser.html", null ],
    [ "AR.Drone.Client.NetworkConfiguration", "class_a_r_1_1_drone_1_1_client_1_1_network_configuration.html", null ],
    [ "AR.Drone.Avionics.Apparatus.Output", "class_a_r_1_1_drone_1_1_avionics_1_1_apparatus_1_1_output.html", null ],
    [ "AR.Drone.Client.Video.Native.parrot_video_encapsulation_t", "struct_a_r_1_1_drone_1_1_client_1_1_video_1_1_native_1_1parrot__video__encapsulation__t.html", null ],
    [ "AR.Drone.Avionics.Apparatus.Input.Limits.Pitch", "class_a_r_1_1_drone_1_1_avionics_1_1_apparatus_1_1_input_1_1_limits_1_1_pitch.html", null ],
    [ "AR.Drone.Video.PixelFormatConverter", "class_a_r_1_1_drone_1_1_video_1_1_pixel_format_converter.html", null ],
    [ "FFmpeg.AutoGen.pp_context", "struct_f_fmpeg_1_1_auto_gen_1_1pp__context.html", null ],
    [ "FFmpeg.AutoGen.pp_mode", "struct_f_fmpeg_1_1_auto_gen_1_1pp__mode.html", null ],
    [ "Queue", null, [
      [ "MaxBuffer< T >", "class_max_buffer.html", null ]
    ] ],
    [ "FFmpeg.AutoGen.RcOverride", "struct_f_fmpeg_1_1_auto_gen_1_1_rc_override.html", null ],
    [ "FFmpeg.AutoGen.ReSampleContext", "struct_f_fmpeg_1_1_auto_gen_1_1_re_sample_context.html", null ],
    [ "AR.Drone.Avionics.Apparatus.Input.Limits.Roll", "class_a_r_1_1_drone_1_1_avionics_1_1_apparatus_1_1_input_1_1_limits_1_1_roll.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.screen_point_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1screen__point__t.html", null ],
    [ "AR.Drone.Client.Configuration.SectionBase", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_section_base.html", [
      [ "AR.Drone.Client.Configuration.ControlSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_control_section.html", null ],
      [ "AR.Drone.Client.Configuration.CustomSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_custom_section.html", null ],
      [ "AR.Drone.Client.Configuration.DetectSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_detect_section.html", null ],
      [ "AR.Drone.Client.Configuration.GeneralSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_general_section.html", null ],
      [ "AR.Drone.Client.Configuration.GpsSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_gps_section.html", null ],
      [ "AR.Drone.Client.Configuration.LedsSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_leds_section.html", null ],
      [ "AR.Drone.Client.Configuration.NetworkSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_network_section.html", null ],
      [ "AR.Drone.Client.Configuration.PicSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_pic_section.html", null ],
      [ "AR.Drone.Client.Configuration.SyslogSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_syslog_section.html", null ],
      [ "AR.Drone.Client.Configuration.UserboxSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_userbox_section.html", null ],
      [ "AR.Drone.Client.Configuration.VideoSection", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_video_section.html", null ]
    ] ],
    [ "AR.Drone.Client.Configuration.Settings", "class_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_settings.html", null ],
    [ "FFmpeg.AutoGen.SwrContext", "struct_f_fmpeg_1_1_auto_gen_1_1_swr_context.html", null ],
    [ "FFmpeg.AutoGen.SwsContext", "struct_f_fmpeg_1_1_auto_gen_1_1_sws_context.html", null ],
    [ "FFmpeg.AutoGen.SwsFilter", "struct_f_fmpeg_1_1_auto_gen_1_1_sws_filter.html", null ],
    [ "FFmpeg.AutoGen.SwsVector", "struct_f_fmpeg_1_1_auto_gen_1_1_sws_vector.html", null ],
    [ "AR.Drone.Client.Configuration.UserboxCommand", "struct_a_r_1_1_drone_1_1_client_1_1_configuration_1_1_userbox_command.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Math.vector21_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_math_1_1vector21__t.html", null ],
    [ "AR.Drone.Data.Navigation.Vector3", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_vector3.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Math.vector31_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_math_1_1vector31__t.html", null ],
    [ "AR.Drone.Data.Navigation.Native.Options.velocities_t", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_native_1_1_options_1_1velocities__t.html", null ],
    [ "AR.Drone.Data.Navigation.Video", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_video.html", null ],
    [ "AR.Drone.Video.VideoFrame", "class_a_r_1_1_drone_1_1_video_1_1_video_frame.html", null ],
    [ "AR.Drone.Client.Video.VideoFrameTypeConverter", "class_a_r_1_1_drone_1_1_client_1_1_video_1_1_video_frame_type_converter.html", null ],
    [ "AR.Drone.Data.VideoPacket", "struct_a_r_1_1_drone_1_1_data_1_1_video_packet.html", null ],
    [ "AR.Drone.Data.Navigation.Wifi", "struct_a_r_1_1_drone_1_1_data_1_1_navigation_1_1_wifi.html", null ],
    [ "NativeWifi.Wlan", "class_native_wifi_1_1_wlan.html", null ],
    [ "NativeWifi.Wlan.WlanAssociationAttributes", "struct_native_wifi_1_1_wlan_1_1_wlan_association_attributes.html", null ],
    [ "NativeWifi.Wlan.WlanAvailableNetwork", "struct_native_wifi_1_1_wlan_1_1_wlan_available_network.html", null ],
    [ "NativeWifi.Wlan.WlanBssEntry", "struct_native_wifi_1_1_wlan_1_1_wlan_bss_entry.html", null ],
    [ "NativeWifi.WlanClient", "class_native_wifi_1_1_wlan_client.html", null ],
    [ "NativeWifi.Wlan.WlanConnectionAttributes", "struct_native_wifi_1_1_wlan_1_1_wlan_connection_attributes.html", null ],
    [ "NativeWifi.Wlan.WlanConnectionNotificationData", "struct_native_wifi_1_1_wlan_1_1_wlan_connection_notification_data.html", null ],
    [ "NativeWifi.Wlan.WlanConnectionParameters", "struct_native_wifi_1_1_wlan_1_1_wlan_connection_parameters.html", null ],
    [ "NativeWifi.WlanClient.WlanInterface", "class_native_wifi_1_1_wlan_client_1_1_wlan_interface.html", null ],
    [ "NativeWifi.Wlan.WlanInterfaceInfo", "struct_native_wifi_1_1_wlan_1_1_wlan_interface_info.html", null ],
    [ "NativeWifi.Wlan.WlanNotificationData", "struct_native_wifi_1_1_wlan_1_1_wlan_notification_data.html", null ],
    [ "NativeWifi.Wlan.WlanProfileInfo", "struct_native_wifi_1_1_wlan_1_1_wlan_profile_info.html", null ],
    [ "NativeWifi.Wlan.WlanRateSet", "struct_native_wifi_1_1_wlan_1_1_wlan_rate_set.html", null ],
    [ "NativeWifi.Wlan.WlanSecurityAttributes", "struct_native_wifi_1_1_wlan_1_1_wlan_security_attributes.html", null ],
    [ "AR.Drone.Avionics.Apparatus.Input.Limits.Yaw", "class_a_r_1_1_drone_1_1_avionics_1_1_apparatus_1_1_input_1_1_limits_1_1_yaw.html", null ]
];